"""Three-point quadrature in PARAMETER space, with measurements generated by Kratos.

    alpha_j = alpha_mean + z_j * alpha_std,     z = (-sqrt3, 0, +sqrt3)
    w       = (1/6, 2/3, 1/6)
    E_j     = alpha_j * E_ref
    u_j     = G(E_j)          <- the real Kratos forward solve, one fresh model each
    u_hat_j = u_j             <- zero-mean noise: its expected value is zero

Each u_hat_j then drives its own independent Phase 2 inversion.

WHY THE PREVIOUS DISPLACEMENT-SPACE VERSION WAS WRONG
-----------------------------------------------------
It placed the support points at u_hat_mean +- sqrt3 * u_hat_std, i.e. symmetrically in
DISPLACEMENT space. The map from stiffness to displacement is inverse, so a symmetric
interval in u is strongly asymmetric in alpha: equal steps down and up in u became
alpha steps of very different size, and the recovered spread came out ~89% too large
with a pronounced right skew. Gauss-Hermite is exact for the moments of the variable
its nodes are placed in -- and the quantity whose mean and sd we want to recover is
alpha, not u. Placing the nodes in alpha and pushing them THROUGH the forward model
fixes this exactly, whatever the model's nonlinearity happens to be.

That method is removed. measured_data_collapsed.csv is no longer read here; it remains
useful only for comparison.

DIMENSIONALITY
--------------
The three-point rule below is the one-dimensional Gauss-Hermite rule and assumes a
single uncertain parameter. A future version with several uncertain parameters, several
material zones, or correlated inputs would need a multidimensional rule -- a tensor or
sparse Smolyak grid, or an unscented/sigma-point set -- not this one applied per
parameter. The forward evaluation itself is already model-independent: it goes through
the existing KratosForwardModel interface and contains no beam formula, no u_ref/alpha
scaling, and no hard-coded displacement.
"""
import csv
import gc
import json
import os
import sys
import time

import numpy as np
import KratosMultiphysics as Kratos

from bayesian_analysis import BayesianAnalysis
from kratos_forward_model import KratosForwardModel

# probabilists' three-point Gauss-Hermite rule: exact for polynomials up to degree 5
Z_VALUES = np.array([-np.sqrt(3.0), 0.0, np.sqrt(3.0)])
WEIGHTS = np.array([1.0 / 6.0, 2.0 / 3.0, 1.0 / 6.0])
CASE_NAMES = ["point_1_low", "point_2_central", "point_3_high"]

MEASURED_HEADER = "#,type,name,location_0,location_1,location_2,value\n"


def GetDefaultParameters():
    return Kratos.Parameters("""{
        "enabled"                 : false,
        "support_space"           : "alpha",
        "alpha_mean"              : 1.0,
        "alpha_std"               : 0.1,
        "E_ref"                   : 206900000000.0,
        "measurement_noise_sigma" : 3.788097e-08,
        "measurement_generation"  : "zero_mean_noise",
        "input_path"              : "three_point_inputs",
        "output_path"             : "output_three_point",
        "combined_sample_count"   : 100000,
        "base_random_seed"        : 20260802,
        "resume"                  : false,
        "make_plots"              : true,
        "dry_run"                 : false
    }""")


# --------------------------------------------------------------------------- helpers
def one_line(exc):
    return " ".join(f"{type(exc).__name__}: {exc}".split())[:400]


def rebase_output_path(original, case_output_dir):
    """'output/vtk_output' -> '<case_dir>/vtk_output';  'output' -> '<case_dir>'."""
    parts = [p for p in original.replace("\\", "/").split("/") if p not in ("", ".")]
    return os.path.join(case_output_dir, *parts[1:]) if len(parts) > 1 else case_output_dir


def build_alpha_points(alpha_mean, alpha_std):
    """Support points in PARAMETER space, verified against the moments they encode."""
    if not np.isfinite(alpha_mean) or not np.isfinite(alpha_std):
        raise ValueError("alpha_mean and alpha_std must be finite")
    if alpha_std < 0.0:
        raise ValueError(f"alpha_std must be >= 0, got {alpha_std}")

    points = alpha_mean + Z_VALUES * alpha_std
    if np.any(points <= 0.0):
        raise ValueError(f"support points {points} contain a non-positive alpha; "
                         "reduce alpha_std or raise alpha_mean")

    weighted_mean = float(np.sum(WEIGHTS * points))
    weighted_var = float(np.sum(WEIGHTS * (points - weighted_mean) ** 2))
    if abs(weighted_mean - alpha_mean) > 1e-12 * max(abs(alpha_mean), 1.0):
        raise AssertionError(f"weighted mean {weighted_mean} != alpha_mean {alpha_mean}")
    if abs(np.sqrt(weighted_var) - alpha_std) > 1e-12 * max(alpha_std, 1.0):
        raise AssertionError(f"weighted sd {np.sqrt(weighted_var)} != alpha_std {alpha_std}")
    return points, weighted_mean, float(np.sqrt(weighted_var))


def forward_sensor_metadata(settings):
    """Sensor type/name/location straight from the existing sensor definition file."""
    import sensors as sensor_tools
    return sensor_tools.read_sensors(settings["sensor_data_file"].GetString())


def generate_measurements(alpha_points, base_parameters, E_ref, sigma_noise,
                          generation_mode, base_seed):
    """u_j = G(E_j) through the real Kratos forward model, one fresh model per point.

    KratosForwardModel.Evaluate(theta) multiplies each zone's reference stiffness by
    theta, so passing alpha_j applies E_j = alpha_j * E_ref exactly. Nothing in here
    knows the model is a beam, and no analytical scaling is used.
    """
    settings = base_parameters["forward_model"]
    responses, sensors = [], None

    for j, alpha in enumerate(alpha_points):
        model = Kratos.Model()                      # never reused between evaluations
        entries = [base_parameters["parameters"][i]
                   for i in range(base_parameters["parameters"].size())]
        forward = KratosForwardModel(model, settings.Clone(), entries)

        model_ref = float(np.atleast_1d(forward.refs)[0])
        if abs(model_ref - E_ref) > 1e-9 * abs(E_ref):
            raise ValueError(f"configured E_ref {E_ref:.6e} does not match the model's "
                             f"reference stiffness {model_ref:.6e}; the materials file "
                             "and the configuration disagree")

        u = np.asarray(forward.Evaluate([float(alpha)]), dtype=float)
        if u.size == 0 or not np.all(np.isfinite(u)):
            raise ValueError(f"case {j + 1}: forward model returned a non-finite response")
        if sensors is None:
            sensors = forward_sensor_metadata(settings)
        if u.size != len(sensors):
            raise ValueError(f"case {j + 1}: model returned {u.size} values for "
                             f"{len(sensors)} sensors")

        responses.append(u)
        forward.Finalize()
        del forward, model
        gc.collect()

    responses = np.array(responses)

    if generation_mode == "zero_mean_noise":
        # the expected value of zero-mean noise is zero. With only three points, three
        # random draws would visibly move the recovered mean and sd.
        measurements = responses.copy()
        seeds = [None] * len(alpha_points)
    elif generation_mode == "sampled_noise":
        measurements = np.empty_like(responses)
        seeds = []
        for j in range(len(alpha_points)):
            seed = base_seed + 1000 + j
            rng = np.random.default_rng(seed)
            measurements[j] = responses[j] + rng.normal(0.0, sigma_noise,
                                                        responses[j].shape)
            seeds.append(seed)
    else:
        raise ValueError(f"measurement_generation must be 'zero_mean_noise' or "
                         f"'sampled_noise', got '{generation_mode}'")

    return responses, measurements, sensors, seeds


def write_case_measurement_file(path, sensors, values):
    """Only the seven columns the existing Likelihood expects."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="") as f:
        f.write(MEASURED_HEADER)
        for i, (s, v) in enumerate(zip(sensors, values), 1):
            f.write(f"{i},{s['type']},{s['name']},{s['location'][0]},{s['location'][1]},"
                    f"{s['location'][2]},{v:.16e}\n")


def summarize(alpha_samples, E_ref):
    E_samples = E_ref * alpha_samples
    summary = {}
    for tag, data in (("alpha", alpha_samples), ("E", E_samples)):
        summary[f"{tag}_posterior_mean"] = float(np.mean(data))
        summary[f"{tag}_posterior_sd"] = float(np.std(data, ddof=1)) if data.size > 1 else 0.0
        summary[f"{tag}_posterior_median"] = float(np.median(data))
        summary[f"{tag}_ci_2_5"] = float(np.percentile(data, 2.5))
        summary[f"{tag}_ci_97_5"] = float(np.percentile(data, 97.5))
    return summary, E_samples


# ------------------------------------------------------------------- one inversion
def run_case(case_name, z, weight, measured_file, case_output_dir,
             base_parameters, sigma_noise, seed):
    """One independent Phase 2 inversion. Sees only u_hat and the broad uniform prior;
    alpha_true and E_true are never passed in."""
    parameters = base_parameters.Clone()
    for block in ("three_point_inference", "batch_inference"):
        if parameters.Has(block):
            parameters.RemoveValue(block)

    parameters["likelihood"]["measured_data_file"].SetString(measured_file)
    parameters["likelihood"]["noise_model"]["sigma"].SetDouble(float(sigma_noise))
    parameters["sampler_settings"]["Parameters"]["random_seed"].SetInt(int(seed))

    os.makedirs(case_output_dir, exist_ok=True)
    for i in range(parameters["output_processes"].size()):
        settings = parameters["output_processes"][i]["Parameters"]
        if settings.Has("output_path"):
            settings["output_path"].SetString(
                rebase_output_path(settings["output_path"].GetString(), case_output_dir))

    model = Kratos.Model()
    analysis = BayesianAnalysis(model, parameters)
    analysis.Initialize()

    n_sensors = len(analysis.forward_model.located)
    u_hat = np.asarray(analysis.likelihood.u_hat, dtype=float)
    if u_hat.size != n_sensors:
        raise ValueError(f"measured vector has {u_hat.size} entries but the model has "
                         f"{n_sensors} sensors")
    if not np.all(np.isfinite(u_hat)):
        raise ValueError("non-finite measured value")

    probe = np.asarray(analysis.forward_model.Evaluate([1.0]), dtype=float)
    if probe.size != n_sensors or not np.all(np.isfinite(probe)):
        raise ValueError("forward model returned a non-finite or wrongly sized response")
    if not np.isfinite(analysis.likelihood([1.0])):
        raise ValueError("likelihood is non-finite at alpha = 1")
    analysis.forward_model.n_solves = 0

    analysis.RunSolutionLoop()
    analysis.Finalize()

    E_ref = float(np.atleast_1d(analysis.forward_model.refs)[0])
    posterior = np.asarray(analysis.sampler.levels[-1], dtype=float)
    if posterior.ndim == 1:
        posterior = posterior.reshape(-1, 1)
    if posterior.size == 0:
        raise ValueError("empty final posterior level")
    alpha_samples = posterior[:, 0]
    if not np.all(np.isfinite(alpha_samples)):
        raise ValueError("non-finite posterior draws")

    summary, E_samples = summarize(alpha_samples, E_ref)
    summary.update({
        "case_name": case_name, "status": "ok",
        "z_value": float(z), "weight": float(weight),
        "measurement": float(u_hat[0]),
        "measurement_noise_sigma": float(sigma_noise),
        "number_of_posterior_samples": int(alpha_samples.size),
        "number_of_forward_solves": int(analysis.forward_model.n_solves),
        "number_of_levels": int(len(analysis.sampler.q)),
        "random_seed": int(seed),
        "measured_data_file": measured_file,
        "E_ref": E_ref, "error_message": "",
    })

    np.savez_compressed(os.path.join(case_output_dir, "posterior_samples.npz"),
                        alpha=alpha_samples, E=E_samples,
                        q=np.asarray(analysis.sampler.q, dtype=float),
                        E_ref=np.array([E_ref]), weight=np.array([weight]),
                        z=np.array([z]))
    with open(os.path.join(case_output_dir, "posterior_summary.json"), "w") as f:
        json.dump(summary, f, indent=2)

    del analysis, model
    gc.collect()
    return summary


def load_completed_case(case_output_dir):
    """Skip a case only if BOTH artefacts exist and parse as a successful run."""
    npz = os.path.join(case_output_dir, "posterior_samples.npz")
    summary_file = os.path.join(case_output_dir, "posterior_summary.json")
    if not (os.path.isfile(npz) and os.path.isfile(summary_file)):
        return None
    try:
        with open(summary_file) as f:
            summary = json.load(f)
        with np.load(npz) as data:
            alpha = np.asarray(data["alpha"], dtype=float)
        if summary.get("status") != "ok" or alpha.size == 0 or not np.all(np.isfinite(alpha)):
            return None
        return summary
    except (OSError, ValueError, KeyError):
        return None


# ------------------------------------------------------------------- the combination
def combine_posteriors(case_dirs, weights, total, seed):
    """Weighted mixture by resampling. Equal-size concatenation would silently reweight
    the three cases to 1/3 each, which is not the quadrature rule."""
    alpha_sets, E_sets = [], []
    for path in case_dirs:
        with np.load(os.path.join(path, "posterior_samples.npz")) as data:
            alpha_sets.append(np.asarray(data["alpha"], dtype=float))
            E_sets.append(np.asarray(data["E"], dtype=float))

    rng = np.random.default_rng(seed)
    probabilities = list(weights[:-1] / weights.sum())
    probabilities.append(1.0 - sum(probabilities))       # guards float round-off
    counts = rng.multinomial(int(total), probabilities)

    combined_alpha = np.concatenate([rng.choice(a, size=int(c), replace=True)
                                     for a, c in zip(alpha_sets, counts)])
    combined_E = np.concatenate([rng.choice(e, size=int(c), replace=True)
                                 for e, c in zip(E_sets, counts)])
    order = rng.permutation(combined_alpha.size)
    return combined_alpha[order], combined_E[order], counts


def population_statistics(means, sds, weights):
    """Between-case sd is the recovered POPULATION spread -- variability of the three
    posterior MEANS only. The mixture sd adds within-posterior inference uncertainty on
    top and is a different quantity that must never be quoted as the population sd."""
    weights = weights / weights.sum()
    mu = float(np.sum(weights * means))
    between = float(np.sqrt(np.sum(weights * (means - mu) ** 2)))
    mixture = float(np.sqrt(np.sum(weights * (sds ** 2 + (means - mu) ** 2))))
    return mu, between, mixture


# ------------------------------------------------------------------------------ plots
def make_plots(cases, combined_alpha, stats, target, output_dir, E_ref):
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not available - skipping plots")
        return []

    ok = [c for c in cases if c["status"] == "ok"]
    if not ok:
        return []

    colors = plt.cm.viridis(np.linspace(0.15, 0.9, 3))
    NAVY = "#1a3a5a"
    MAIN = matplotlib.colors.to_rgba("#4878a8")
    written = []

    def save(fig, name):
        path = os.path.abspath(os.path.join(output_dir, name))
        os.makedirs(os.path.dirname(path), exist_ok=True)
        try:
            fig.savefig(path, dpi=150, bbox_inches="tight")
        except OSError as exc:
            path = os.path.abspath(name)
            print(f"  could not write into {output_dir} ({exc.strerror}); using {path}")
            fig.savefig(path, dpi=150, bbox_inches="tight")
        plt.close(fig)
        written.append(path)

    def normal_pdf(x, mean, sd):
        return np.exp(-0.5 * ((x - mean) / sd) ** 2) / (sd * np.sqrt(2.0 * np.pi))

    def gpa_axis(ax):
        secondary = ax.secondary_xaxis(
            "top", functions=(lambda x: x * E_ref / 1e9, lambda x: x * 1e9 / E_ref))
        secondary.set_xlabel("E [GPa]", fontsize=9)

    mu = stats["alpha_recovered_mean"]
    between = stats["alpha_between_case_sd"]
    means = np.array([c["alpha_posterior_mean"] for c in ok])
    weights = np.array([c["weight"] for c in ok])

    # ---- Plot A: the recovered population, from the three weighted means only
    fig, ax = plt.subplots(figsize=(7.4, 4.4))
    lo = min(means.min(), mu - 4 * max(between, 1e-9), target[0] - 4 * target[1])
    hi = max(means.max(), mu + 4 * max(between, 1e-9), target[0] + 4 * target[1])
    grid = np.linspace(lo, hi, 600)

    if target[1] > 0:
        ax.plot(grid, normal_pdf(grid, target[0], target[1]), color="black", lw=2,
                label=rf"Phase 1 target $\mathcal{{N}}$({target[0]:.4f}, {target[1]:.4f})")
    if between > 0:
        ax.plot(grid, normal_pdf(grid, mu, between), color="crimson", ls="--", lw=2,
                label=rf"recovered $\mathcal{{N}}$({mu:.4f}, {between:.4f})")
    height = normal_pdf(mu, mu, between) if between > 0 else 1.0
    for m, w, c, color in zip(means, weights, ok, colors):
        ax.vlines(m, 0.0, height * w * 3.0, color=color, lw=2.5)
        ax.plot(m, height * w * 3.0, "o", color=color, ms=9,
                label=rf"{c['case_name']}:  $\alpha$ = {m:.4f},  $w$ = {w:.4f}")
    ax.axvline(mu, color=NAVY, lw=1.6)
    for s in (mu - between, mu + between):
        ax.axvline(s, color=NAVY, lw=1.0, ls=":")
    ax.set_xlabel(r"$\alpha = E/E_{ref}$")
    ax.set_ylabel("population density")
    ax.set_title("Recovered population from three weighted parameter-space points",
                 fontsize=11)
    ax.legend(frameon=False, fontsize=8)
    gpa_axis(ax)
    save(fig, "plotA_recovered_population.png")

    # ---- Plot B: the full posterior mixture, a different quantity
    mix = stats["alpha_total_mixture_sd"]
    fig, ax = plt.subplots(figsize=(7.4, 4.4))
    ax.hist(combined_alpha, bins=80, density=True, color=MAIN, edgecolor="white",
            label=f"weighted mixture (n = {combined_alpha.size})")
    ax.axvline(combined_alpha.mean(), color=NAVY, lw=1.8,
               label=rf"mean $\alpha$ = {combined_alpha.mean():.4f} $\pm$ {mix:.4f}")
    for s in (mu - mix, mu + mix):
        ax.axvline(s, color=NAVY, lw=1.0, ls=":")
    for m, color in zip(means, colors):
        ax.axvline(m, color=color, lw=1.2, ls=":")
    ax.set_xlabel(r"$\alpha = E/E_{ref}$")
    ax.set_ylabel("density")
    ax.set_title("Weighted posterior mixture including inference uncertainty\n"
                 "its sd holds BOTH between-case population variability AND\n"
                 "within-posterior uncertainty; it is not the recovered population sd",
                 fontsize=9.5)
    ax.legend(frameon=False, fontsize=8)
    gpa_axis(ax)
    save(fig, "plotB_posterior_mixture.png")

    # ---- Plot C: ONE box for the recovered population, E = mu +- between-case sd
    mu_E = stats["E_recovered_mean"] / 1e9
    sd_E = stats["E_between_case_sd"] / 1e9
    tgt_E = target[0] * E_ref / 1e9
    tgt_sd_E = target[1] * E_ref / 1e9

    fig, ax = plt.subplots(figsize=(7.4, 3.0))

    # the recovered population is the normal N(mu_E, sd_E); its quartiles are analytic
    box = [dict(med=mu_E, q1=mu_E - 0.6745 * sd_E, q3=mu_E + 0.6745 * sd_E,
                whislo=mu_E - 1.96 * sd_E, whishi=mu_E + 1.96 * sd_E, fliers=[])]
    bp = ax.bxp(box, vert=False, widths=0.5, patch_artist=True, showfliers=False,
                medianprops=dict(color="white", lw=2.0),
                whiskerprops=dict(color=NAVY, lw=1.3),
                capprops=dict(color=NAVY, lw=1.3),
                boxprops=dict(facecolor=MAIN, edgecolor=NAVY, lw=1.3))

    if tgt_sd_E > 0:
        ax.axvspan(tgt_E - tgt_sd_E, tgt_E + tgt_sd_E, color="crimson", alpha=0.10,
                   zorder=0, label=rf"Phase 1 target $\pm 1\sigma$ = $\pm${tgt_sd_E:.2f} GPa")
    ax.axvline(tgt_E, color="crimson", ls="--", lw=1.5, zorder=1,
               label=rf"Phase 1 target mean = {tgt_E:.2f} GPa")
    ax.plot(mu_E, 1, marker="D", ms=7, color=NAVY, mec="white", mew=0.9, zorder=5,
            label=rf"recovered {mu_E:.2f} $\pm$ {sd_E:.2f} GPa")

    # the headline number, printed on the figure itself
    ax.text(mu_E, 1.40, rf"$E$ = {mu_E:.2f} $\pm$ {sd_E:.2f} GPa",
            ha="center", va="bottom", fontsize=13, color=NAVY, zorder=6)

    ax.set_yticks([])
    ax.set_ylim(0.55, 1.55)
    ax.set_xlabel("E [GPa]")
    ax.set_title("Recovered population of Young's modulus\n"
                 "box = interquartile range, whiskers = 95% of the population",
                 fontsize=10)
    ax.legend(frameon=False, fontsize=8, loc="upper left", bbox_to_anchor=(0.0, -0.28),
              ncol=1)
    ax.grid(True, axis="x", alpha=0.25)
    for side in ("left", "right", "top"):
        ax.spines[side].set_visible(False)

    secondary = ax.secondary_xaxis(
        "top", functions=(lambda x: x * 1e9 / E_ref, lambda a: a * E_ref / 1e9))
    secondary.set_xlabel(r"$\alpha = E/E_{ref}$", fontsize=9)

    save(fig, "plotC_recovered_population_box.png")

    return written


# ------------------------------------------------------------------------ controller
def apply_cli_overrides(settings):
    argv = sys.argv[1:]
    if "--dry-run" in argv:
        settings["dry_run"].SetBool(True)
    if "--no-plots" in argv:
        settings["make_plots"].SetBool(False)
    if "--resume" in argv:
        settings["resume"].SetBool(True)


def RunThreePoint(project_parameters):
    settings = project_parameters["three_point_inference"]
    settings.ValidateAndAssignDefaults(GetDefaultParameters())
    apply_cli_overrides(settings)

    support_space = settings["support_space"].GetString()
    if support_space != "alpha":
        raise ValueError(
            f"support_space = '{support_space}' is not supported. Only 'alpha' is "
            "implemented: placing the nodes in displacement space was the previous, "
            "incorrect method and has been removed rather than kept as a fallback.")

    alpha_mean = settings["alpha_mean"].GetDouble()
    alpha_std = settings["alpha_std"].GetDouble()
    E_ref = settings["E_ref"].GetDouble()
    sigma_noise = settings["measurement_noise_sigma"].GetDouble()
    generation_mode = settings["measurement_generation"].GetString()
    input_root = settings["input_path"].GetString()
    output_root = settings["output_path"].GetString()
    base_seed = settings["base_random_seed"].GetInt()
    resume = settings["resume"].GetBool()
    dry_run = settings["dry_run"].GetBool()

    if not np.isfinite(sigma_noise) or sigma_noise <= 0.0:
        raise ValueError(f"measurement_noise_sigma must be positive, got {sigma_noise}")

    alpha_points, wm, wsd = build_alpha_points(alpha_mean, alpha_std)
    E_points = alpha_points * E_ref

    print(f"\nsupport space     : {support_space} (parameter space)")
    print(f"alpha ~ N({alpha_mean}, {alpha_std})   E_ref = {E_ref:.6e} Pa\n")
    print(f"{'case':>18} {'z':>14} {'weight':>10} {'alpha':>16} {'E [GPa]':>14}")
    for j, name in enumerate(CASE_NAMES):
        print(f"{name:>18} {Z_VALUES[j]:>+14.10f} {WEIGHTS[j]:>10.6f} "
              f"{alpha_points[j]:>16.10f} {E_points[j] / 1e9:>14.6f}")
    print(f"\nweighted alpha mean : {wm:.16f}   (target {alpha_mean})")
    print(f"weighted alpha sd   : {wsd:.16f}   (target {alpha_std})")

    if dry_run:
        print("\nDRY RUN: support points computed and moments verified. "
              "No Kratos model was built and no SMC was run.")
        return {"dry_run": True, "alpha_points": alpha_points.tolist(),
                "E_points": E_points.tolist()}

    # ------------------------------------------------- generate the three measurements
    print(f"\ngenerating measurements with the Kratos forward model "
          f"({generation_mode})...")
    t_gen = time.time()
    u_true, u_hat, sensors, gen_seeds = generate_measurements(
        alpha_points, project_parameters, E_ref, sigma_noise, generation_mode, base_seed)
    print(f"done in {time.time() - t_gen:.0f} s\n")

    print(f"{'case':>18} {'alpha_true':>14} "
          + " ".join(f"{'u_true [' + s['name'] + ']':>28}" for s in sensors))
    for j, name in enumerate(CASE_NAMES):
        print(f"{name:>18} {alpha_points[j]:>14.10f} "
              + " ".join(f"{u_true[j, i]:>28.16e}" for i in range(len(sensors))))

    measured_files = []
    for j, name in enumerate(CASE_NAMES):
        case_input_dir = os.path.join(input_root, name)
        path = os.path.join(case_input_dir, "measured_data.csv")
        write_case_measurement_file(path, sensors, u_hat[j])
        measured_files.append(path)

        with open(os.path.join(case_input_dir, "metadata.json"), "w") as f:
            json.dump({
                "case_name": name,
                "z_value": float(Z_VALUES[j]),
                "weight": float(WEIGHTS[j]),
                "alpha_true": float(alpha_points[j]),
                "E_true": float(E_points[j]),
                "u_true": u_true[j].tolist(),
                "u_hat": u_hat[j].tolist(),
                "measurement_generation": generation_mode,
                "likelihood_noise_sigma": float(sigma_noise),
                "random_seed": gen_seeds[j],
            }, f, indent=2)
        print(f"wrote {path}")

    # ------------------------------------------------------------------- three solves
    os.makedirs(output_root, exist_ok=True)
    cases = []
    t_start = time.time()

    for j, name in enumerate(CASE_NAMES):
        case_output_dir = os.path.join(output_root, name)
        seed = base_seed + j + 1

        summary = load_completed_case(case_output_dir) if resume else None
        if summary is not None:
            print(f"\n[{j + 1}/3] {name}: resumed from disk")
        else:
            print(f"\n[{j + 1}/3] {name}: alpha_true = {alpha_points[j]:.10f}, "
                  f"u = {u_hat[j, 0]:.10e}, seed {seed}", flush=True)
            t0 = time.time()
            try:
                summary = run_case(name, Z_VALUES[j], WEIGHTS[j], measured_files[j],
                                   case_output_dir, project_parameters, sigma_noise, seed)
                print(f"    alpha = {summary['alpha_posterior_mean']:.6f} "
                      f"+- {summary['alpha_posterior_sd']:.6f}   "
                      f"(true {alpha_points[j]:.6f}, "
                      f"{summary['number_of_forward_solves']} solves, "
                      f"{time.time() - t0:.0f} s)")
            except Exception as exc:
                summary = {"case_name": name, "status": "failed",
                           "error_message": one_line(exc),
                           "z_value": float(Z_VALUES[j]), "weight": float(WEIGHTS[j])}
                print(f"    FAILED: {summary['error_message']}")

        # truth values attached AFTER inference, for postprocessing only
        summary["case_output_dir"] = case_output_dir
        summary["alpha_true"] = float(alpha_points[j])
        summary["E_true"] = float(E_points[j])
        summary["u_true"] = float(u_true[j, 0])
        cases.append(summary)

    ok = [c for c in cases if c["status"] == "ok"]
    combined_dir = os.path.join(output_root, "combined")
    os.makedirs(combined_dir, exist_ok=True)

    with open(os.path.join(combined_dir, "case_summary.csv"), "w", newline="") as f:
        columns = ["case_name", "status", "z_value", "weight", "alpha_true", "E_true",
                   "u_true", "measurement", "measurement_noise_sigma",
                   "number_of_posterior_samples", "number_of_forward_solves",
                   "alpha_posterior_mean", "alpha_posterior_sd", "alpha_posterior_median",
                   "alpha_ci_2_5", "alpha_ci_97_5",
                   "E_posterior_mean", "E_posterior_sd", "E_posterior_median",
                   "E_ci_2_5", "E_ci_97_5", "error_message"]
        writer = csv.DictWriter(f, fieldnames=columns, extrasaction="ignore")
        writer.writeheader()
        for c in cases:
            writer.writerow(c)

    if len(ok) < 3:
        print(f"\n{3 - len(ok)} of 3 cases failed; combination skipped.")
        return {"status": "incomplete", "cases": cases}

    # ------------------------------------------------------------------- combination
    weights = np.array([c["weight"] for c in ok])
    combined_alpha, combined_E, counts = combine_posteriors(
        [c["case_output_dir"] for c in ok], weights,
        settings["combined_sample_count"].GetInt(), base_seed)

    stats = {}
    for tag in ("alpha", "E"):
        means = np.array([c[f"{tag}_posterior_mean"] for c in ok])
        sds = np.array([c[f"{tag}_posterior_sd"] for c in ok])
        mu, between, mixture = population_statistics(means, sds, weights)
        stats[f"{tag}_recovered_mean"] = mu
        stats[f"{tag}_between_case_sd"] = between
        stats[f"{tag}_total_mixture_sd"] = mixture

    target = (alpha_mean, alpha_std)
    combined = {
        "method": "three-point Gauss-Hermite in alpha (parameter) space",
        "note": ("alpha_between_case_sd is the recovered POPULATION sd; "
                 "alpha_total_mixture_sd additionally contains within-posterior "
                 "inference uncertainty and must NOT be quoted as the population sd"),
        "support_space": support_space,
        "measurement_generation": generation_mode,
        "measurement_noise_sigma": sigma_noise,
        "cases": [c["case_name"] for c in ok],
        "weights": weights.tolist(),
        "z_values": Z_VALUES.tolist(),
        "alpha_true": [c["alpha_true"] for c in ok],
        "E_true": [c["E_true"] for c in ok],
        "u_true": [c["u_true"] for c in ok],
        "alpha_posterior_means": [c["alpha_posterior_mean"] for c in ok],
        "alpha_posterior_sds": [c["alpha_posterior_sd"] for c in ok],
        "E_ref": E_ref,
        "phase1_target_alpha_mean": alpha_mean,
        "phase1_target_alpha_sd": alpha_std,
        "phase1_target_E_mean": alpha_mean * E_ref,
        "phase1_target_E_sd": alpha_std * E_ref,
        "resample_counts": counts.tolist(),
        "combined_sample_count": int(combined_alpha.size),
        "total_forward_solves": int(sum(c["number_of_forward_solves"] for c in ok)),
    }
    combined.update(stats)
    combined["relative_error_alpha_mean"] = float(
        stats["alpha_recovered_mean"] / alpha_mean - 1.0)
    combined["relative_error_alpha_between_sd"] = float(
        stats["alpha_between_case_sd"] / alpha_std - 1.0) if alpha_std > 0 else 0.0

    np.savez_compressed(os.path.join(combined_dir, "combined_posterior_samples.npz"),
                        alpha=combined_alpha, E=combined_E,
                        weights=weights, counts=counts, E_ref=np.array([E_ref]))
    with open(os.path.join(combined_dir, "combined_summary.json"), "w") as f:
        json.dump(combined, f, indent=2)

    if settings["make_plots"].GetBool():
        for path in make_plots(cases, combined_alpha, stats, target, combined_dir, E_ref):
            print(f"plot: {path}")

    # ------------------------------------------------------------------------ report
    print("\n================= three-point summary =================")
    print(f"{'case':>18} {'w':>8} {'alpha_true':>12} {'alpha post':>12} {'post sd':>10}")
    for c in ok:
        print(f"{c['case_name']:>18} {c['weight']:>8.4f} {c['alpha_true']:>12.6f} "
              f"{c['alpha_posterior_mean']:>12.6f} {c['alpha_posterior_sd']:>10.6f}")

    print("\nrecovered population (PRIMARY)")
    print(f"  alpha : mean {stats['alpha_recovered_mean']:.6f}   "
          f"between-case sd {stats['alpha_between_case_sd']:.6f}")
    print(f"  E     : mean {stats['E_recovered_mean']:.6e}   "
          f"between-case sd {stats['E_between_case_sd']:.6e}")
    print("\nPhase 1 target")
    print(f"  alpha : mean {alpha_mean:.6f}   sd {alpha_std:.6f}")
    print(f"  E     : mean {alpha_mean * E_ref:.6e}   sd {alpha_std * E_ref:.6e}")
    print(f"\nrelative error : mean {combined['relative_error_alpha_mean']:+.2%}   "
          f"between-case sd {combined['relative_error_alpha_between_sd']:+.2%}")
    print("\ntotal posterior-mixture sd (population + inference, NOT the population sd)")
    print(f"  alpha : {stats['alpha_total_mixture_sd']:.6f}   "
          f"E : {stats['E_total_mixture_sd']:.6e}")
    print(f"\ntotal forward solves : {combined['total_forward_solves']} "
          "(+3 for measurement generation)")
    print(f"wall clock           : {time.time() - t_start:.0f} s")
    print(f"outputs              : {output_root}")
    return combined
